// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Envios_comercio.Models;

public partial class Producto
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public decimal Precio { get; set; }

    public virtual ICollection<DetallesEnvio> DetallesEnvios { get; set; } = new List<DetallesEnvio>();
}